services:
  backend:
    build: ./backend
    env_file: .env 
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 20s
    ports:
      - "5000:5000"
    command: ["sh", "-c", "flask db upgrade && gunicorn --bind 0.0.0.0:5000 app:create_app"]
    
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge