services:
  - type: web
    name: reservation-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: reservation-db
          property: connectionString
      - key: FLASK_APP
        value: app
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /health
    autoDeploy: true

  - type: web
    name: reservation-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: REACT_APP_API_URL
        value: https://reservation-backend.onrender.com
    autoDeploy: true

databases:
  - name: reservation-db
    databaseName: reservationsdb
    user: reservation_user
    plan: free 