"""Add venue comments

Revision ID: 02d288b28cc8
Revises: 0f62ab4fd82d
Create Date: 2025-06-01 20:18:02.861143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02d288b28cc8'
down_revision = '0f62ab4fd82d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue_comments', sa.Column('rating', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue_comments', 'rating')
    # ### end Alembic commands ###
