"""empty message

Revision ID: 861467f3480f
Revises: c39d74a90481
Create Date: 2025-06-01 17:34:10.504479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '861467f3480f'
down_revision = 'c39d74a90481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('venues', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'longitude')
    op.drop_column('venues', 'latitude')
    # ### end Alembic commands ###
