"""Adding images to venues

Revision ID: af94400b3724
Revises: 02d288b28cc8
Create Date: 2025-06-06 18:54:49.755467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af94400b3724'
down_revision = '02d288b28cc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'image_url')
    # ### end Alembic commands ###
